db:
  image: mysql
  environment:
    MYSQL_DATABASE: ninja
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    MYSQL_ROOT_PASSWORD: mdp

app:
  build: .
  links:
    - db:mysql
  environment:
    - APP_DEBUG=true
    - APP_KEY=invoicekeyinvoicekeyinvoicekey12
    - DB_USERNAME=user
    - DB_PASSWORD=mdp
    - DB_HOST=$MYSQL_PORT
    - DB_DATABASE=ninja
  volumes:
    - ./data/invoice:/var/www/html/logo

web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  volumes_from:
    - app
  ports:
    - 80
